### ISSUE TITLE
Natron's process doesn't hangup when exiting ...

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#207]
_From @ponceto on June 26, 2017 8:34_

### Problem

When exiting  Natron, a process is still living. We have to kill it manually.

### Versions

* **Natron 2.2.8 (deb archive from website)** 
* **OS : Linux Mint 18.1** 

_Copied from original issue: MrKepzie/Natron#1628_

**Comment by devernay** [comment]
@ponceto can you try with the latest RC (>= 2.3.15RC13) ?

**Comment by rodlie** [comment]
NatronRenderer suffers from this on Windows, it's not possible to run a automated unit test on Windows since the renderer stalls on exit several times during a unit test session and I have to manually intervene and kill the running process.

**Comment by devernay** [comment]
@rodlie this is fixed, right?

**Comment by rodlie** [comment]
**Much** better after the upgrade to OIIO 2.12, but still happens sometimes on Windows, depends on how many OIIO read nodes I have.
