### ISSUE TITLE
Export problem when using a plugin

### ISSUE THREAD

**Issue by Ficreet** [NatronGitHub/Natron#425]
Hello,

I use Natron on Windows 10 and when exporting my first project on this software I noticed that the borders of the rounded shapes were not very clear.
I then decided to download a plugin from the community to get an antialiasing on exports (With the node Write): https://github.com/NatronGitHub/natron-plugins/tree/master/Filter/Antialiasing

However, when I request the export to the software, an error occurs and despite my research I did not find how to fix the problem (See screenshot)

Did I install the plugin incorrectly (I put the plugin folder under the installation folder --> Plugins\PyPlugs), or is it a software error, a missing update?

Thank you in advance for your help

I use natron version 2.3.14

![image](https://user-images.githubusercontent.com/42917323/64132739-2b03b400-cdd2-11e9-98b7-06b5a29cf801.png)

**Comment by palbergstrom** [comment]
I also have a problem with jugged edges. No antialiasing for rounded shapes or text. Use the same version on Ubuntu 19.04.

**Comment by rodlie** [comment]
Could you upload a simple project file to replicate the issue?

**Comment by palbergstrom** [comment]
@rodlie 

Like this? Could also be a setting I've missed as I'm not an expert on Natron. Would be happy if that's the case.

[test.zip](https://github.com/NatronGitHub/Natron/files/3612624/test.zip)

**Comment by rodlie** [comment]
Add a solid (or something) as a background should fix the issue.

**Comment by palbergstrom** [comment]
Thanks but still the same. Is it the compression (not good on video formats)? What is the best output for render I can use to avoid that?

**Comment by rodlie** [comment]
The exported avi looks fine here (after I added a solid as background).
![00000001](https://user-images.githubusercontent.com/34516798/64911837-1b1b9680-d727-11e9-967a-b8bd85a32e3b.png)

I would go for ProRes or image sequence for best quality.

**Comment by palbergstrom** [comment]
Yours looks better. I'm on Ubuntu so I don't have ProRes. I haven't used Natron that much but I think it was better in the previous version. Something happened.

**Comment by rodlie** [comment]
Natron includes ProRes support (through FFmpeg), just select MOV as container and ap** as codec.

What was better in previous version(s)?

**Comment by palbergstrom** [comment]
Great :-) I'll try it. 

The antialiasing, as I remember it.

**Comment by rodlie** [comment]
If you have an alpha you need to make sure the output format also supports it.

 * MOV+AP4H (aka ProRes 4444)
 * MOV+PNG
 * MOV+TIFF
 * AVI+FFVH
 * AVI+HFYU

Are the video "formats" that I know support alpha (probably more)

Also remember to check the Alpha checkbox in the write node. Note that the video player also need to "support" it, most media player don't show alpha.

**Comment by palbergstrom** [comment]
Alpha in the write node made a difference. Text looks better but the background solid color is not visible.

**Comment by devernay** [comment]
@Ficreet is this solved?

**Comment by Ficreet** [comment]
Yes, sorry I'm late for the answer.

After the discussion of the other users I started natron using the linux version and without the plugin. It turns out that exporting has worked well. So I don't have a problem anymore!

Thank you to you
